### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by haizeiwanglf** [Hannibal046/nanoDPR#10]
请问在doc2embedding时，保存的npy是  总文章数量/显卡数 ，在保存npy这块是不是有点问题

**Comment by haizeiwanglf** [comment]
还有就是在最后召回的时候，向量没有正则化，这也有影响把

**Comment by Hannibal046** [comment]
你好,请问你具体碰到了什么问题呢?

**Comment by haizeiwanglf** [comment]
你好，第一个问题是在doc2embedding.py文件中，保存的npy并不完整，而是只保存了一张卡上的向量，第二个小问题是test_dpr.py中向量没有正则化

**Comment by Hannibal046** [comment]
doc2embedding.py 会保存每张卡的npy的文件:
https://github.com/Hannibal046/nanoDPR/blob/3d882d7c09f4ae1f3b6379235b947c75f9e76468/doc2embedding.py#L54
https://github.com/Hannibal046/nanoDPR/blob/3d882d7c09f4ae1f3b6379235b947c75f9e76468/doc2embedding.py#L72-L73

关于正则化,nanoDPR参考了DPR的实现; 以及正则化并不是dense retrieval中必须的

**Comment by haizeiwanglf** [comment]
明白了，多谢大佬的回复，非常感谢，浪费大佬时间了
