### ISSUE TITLE
too slow searching

### ISSUE THREAD

**Issue by KimJaehee0725** [Hannibal046/nanoDPR#4]
Hello, Thanks for sharing this awesome repository. 

It helps me a lot to do experiments what i wanted with little effort! 

I tried to test the performance and time efficiency of your configuration, 

and below is my result :
## Performance
Top20 : 72.44
Top100 : 85.57

## Time Cost
Train : 4h 30m
Embedding : 1h 30m
Indexing : about < 10m
searching : 57m

My experiment setup is like this
GPU : one A100 80G
RAM : 2TB
CPU : AMD EPYC 7763 64-Core

The other result seems like similar to your result, except the searching time. 

Could you tell me the suspicious reasons?

Thanks again for your simple and efficient code works!

**Comment by KimJaehee0725** [comment]
i am using the faiss-cpu==1.7.4, faiss-gpu==1.7.2!

**Comment by Hannibal046** [comment]
Hello,

I'm thrilled to hear that you've found this repository beneficial! Regarding the issue you've highlighted, there are a couple of factors to consider:
- The hardware configuration I utilized involved 8 V100 GPUs, as opposed to the single A100 GPU in your setup. The performance disparity you're experiencing could be attributed to the reduced number of negative samples available for each gold sample in your case, which can impact your Top-20 accuracy.
- In terms of search time, I've personally not encountered significant delays. Although your hardware setup appears to be adequate, I can't immediately pinpoint the cause of your extended search times without further information.
Looking forward to assisting you further with this matter.

**Comment by KimJaehee0725** [comment]
I found the reason of the slower faiss search speed :

I am using 2 AMD EPYC 7763 64-Core Processor. 

If someone use faiss search with 2 cpu, it makes extreme slow speed because of the hypter-threading. 

related faiss issuse : https://github.com/facebookresearch/faiss/issues/2953#issue-1804547006

Thanks for your kind reply!
