### ISSUE TITLE
Inquiry About Loading Pretrained DPR Models for Natural Questions Dataset

### ISSUE THREAD

**Issue by FUTUREEEEEE** [Hannibal046/nanoDPR#5]
Hi Hannibal,

Thanks for creating this useful repository. I have been working with the original DPR repository but found it quite complicated. I've turned to your repo as it seems more user-friendly.

I'm currently interested in loading a **pretrained** model from DPR skip the training procedure and reproduce the results for the Natural Questions dataset. Could you please provide some guidance or steps on how to achieve this using your repository?

Looking forward to your response.

Best regards,
Xiaqiang

**Comment by Hannibal046** [comment]
Hi, you could follow the instruction here: https://github.com/Hannibal046/nanoDPR#evaluation
