### ISSUE TITLE
The accuracy of the experimental results is inconsistent with the given results

### ISSUE THREAD

**Issue by ZXLiu** [Hannibal046/nanoDPR#8]
I followed the author's experimental steps step by step, and the result was that the accuracy of top-20 was only 7%, which was far from the accuracy of 79.1% reported by the author. Then I used the trained model provided by the author to embed the Wikipedia data, and then tested it. The result found that the accuracy of top-20 was only 6%, which was also a big difference. May I ask why?

**Comment by Hannibal046** [comment]
could you please show the command you use?

**Comment by ZXLiu** [comment]
I followed your steps in the readme

**Comment by ZXLiu** [comment]
I followed your steps in the readme.If it is convenient, could you please
provide your contact information, such as QQ or wechat? So that we can
communicate more conveniently.Thank you!

Hannibal046 ***@***.***> 于2024年4月15日周一 17:40写道：

**Comment by ZXLiu** [comment]
[image: image.png]
The accuracy rate I got differs greatly from the results you reported on
GitHub. I don't know what the problem is.

Zixin Liu ***@***.***> 于2024年4月15日周一 20:09写道：

**Comment by Hannibal046** [comment]
I prefer to communicate here, because the discussion here could help others encountering the same problem.

I re-check the ckpt and evaluation scripts, it works fine on my side:
![image](https://github.com/Hannibal046/nanoDPR/assets/38466901/80937da4-310b-468f-b0c5-f5c825c9fd72)

So, if you couldn't provide your script, i can't help you with this.

**Comment by Hannibal046** [comment]
you could get the identical results with the following commands:
```bash
git clone https://github.com/Hannibal046/nanoDPR.git
cd nanoDPR

## setup your own python environment and then download the data
python utils/download_data.py --resource data.wikipedia_split.psgs_w100
python utils/download_data.py --resource data.retriever.nq
python utils/download_data.py --resource data.retriever.qas.nq

## download prepared ckpt in the google cloud
pip install gdown
gdown --folder https://drive.google.com/drive/folders/1xJhDq9x8eh9jE3CMRf4HFjXbFc1o1Pmt?usp=drive_link
gdown --folder https://drive.google.com/drive/folders/1TLrHeh81mvUW6QontSlHRhu14b9vhpIU?usp=drive_link

## get doc embedding
accelerate launch doc2embedding.py \
    --pretrained_model_path  doc_encoder \
    --output_dir embedding/nanoDPR

## test
python test_dpr.py --embedding_dir embedding/nanoDPR --pretrained_model_path query_encoder
```

**Comment by ZXLiu** [comment]
Thank you for your detailed reply. I did train query_encoder and
doc_encoder according to what you provided. Then run the accelerate launch
doc2embedding.py command to embed the document, and then run the python
Test_dpr.py command to obtain the result. My doc2embedding.py and
Test_dpr.py scripts are as follows.

Hannibal046 ***@***.***> 于2024年4月15日周一 22:01写道：

**Comment by ZXLiu** [comment]
I found a problem. My server used 4 RTX3090s to divide the Wikipedia
dataset into 4 parts and embed them respectively
wikipedia_shard_0.npy-wikipedia_shard_3.npy. When I read them all and used
faiss to add indexes for query, the accuracy was only 7%. However, when I
only read the part of wikipedia_shard_0.npy and used faiss to add indexes
for the query, I achieved 60% accuracy. So what's going on here?

Zixin Liu ***@***.***> 于2024年4月16日周二 08:55写道：

**Comment by Hannibal046** [comment]
Sorry, but I couldn't reproduce your bug on my side when no more information is provided.

**Comment by ZXLiu** [comment]
Thank you. I figured out my problem. The model I used when embedding
Wikipedia was inconsistent with the model I used when embedding the query,
I corrected the error and now the result is correct.

Hannibal046 ***@***.***> 于2024年4月17日周三 03:40写道：

**Comment by Hannibal046** [comment]
close as solved
